export const seafarers = [
  {
    id: 1,
    fullName: 'John Doe',
    vesselName: 'Sea Explorer',
    nationality: 'USA',
    dateOfBirth: '1985-05-20',
    primaryEmail: 'john.doe@example.com',
    primaryMobile: '+1 555-1234',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP001'
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    vesselName: 'Ocean Voyager',
    nationality: 'Canada',
    dateOfBirth: '1990-02-15',
    primaryEmail: 'jane.smith@example.com',
    primaryMobile: '+1 555-5678',
    primaryStatus: 'Inactive',
    statusDescription: 'Resigned',
    source: 'External',
    employeeID: 'EMP002'
  },
  {
    id: 3,
    fullName: 'Michael Johnson',
    vesselName: 'River Explorer',
    nationality: 'Australia',
    dateOfBirth: '1988-09-08',
    primaryEmail: 'michael.johnson@example.com',
    primaryMobile: '+61 9876-5432',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP003'
  },
  {
    id: 4,
    fullName: 'Emily Davis',
    vesselName: 'Sky Voyager',
    nationality: 'UK',
    dateOfBirth: '1995-04-12',
    primaryEmail: 'emily.davis@example.com',
    primaryMobile: '+44 20 1234 5678',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'External',
    employeeID: 'EMP004'
  },
  {
    id: 5,
    fullName: 'Daniel Wang',
    vesselName: 'Star Cruiser',
    nationality: 'China',
    dateOfBirth: '1983-11-30',
    primaryEmail: 'daniel.wang@example.com',
    primaryMobile: '+86 10 8765 4321',
    primaryStatus: 'Inactive',
    statusDescription: 'Retired',
    source: 'Internal',
    employeeID: 'EMP005'
  },
  {
    id: 6,
    fullName: 'Sophia Miller',
    vesselName: 'Deep Sea Voyager',
    nationality: 'Germany',
    dateOfBirth: '1992-07-18',
    primaryEmail: 'sophia.miller@example.com',
    primaryMobile: '+49 123 456 7890',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'External',
    employeeID: 'EMP006'
  },
  {
    id: 7,
    fullName: 'Ravi Patel',
    vesselName: 'Solar Explorer',
    nationality: 'India',
    dateOfBirth: '1989-03-25',
    primaryEmail: 'ravi.patel@example.com',
    primaryMobile: '+91 98765 43210',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP007'
  },
  {
    id: 8,
    fullName: 'Mia Rodriguez',
    vesselName: 'Galactic Traveler',
    nationality: 'Brazil',
    dateOfBirth: '1998-12-05',
    primaryEmail: 'mia.rodriguez@example.com',
    primaryMobile: '+55 11 98765 4321',
    primaryStatus: 'Inactive',
    statusDescription: 'Resigned',
    source: 'External',
    employeeID: 'EMP008'
  },
  {
    id: 9,
    fullName: 'Liam Johnson',
    vesselName: 'Aqua Explorer',
    nationality: 'Canada',
    dateOfBirth: '1993-09-22',
    primaryEmail: 'liam.johnson@example.com',
    primaryMobile: '+1 555-8765',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP009'
  },
  {
    id: 10,
    fullName: 'Ava Chen',
    vesselName: 'Celestial Voyager',
    nationality: 'China',
    dateOfBirth: '1987-06-14',
    primaryEmail: 'ava.chen@example.com',
    primaryMobile: '+86 21 8765 4321',
    primaryStatus: 'Inactive',
    statusDescription: 'Resigned',
    source: 'External',
    employeeID: 'EMP010'
  },
  {
    id: 11,
    fullName: 'Noah Rodriguez',
    vesselName: 'Skyward Navigator',
    nationality: 'Mexico',
    dateOfBirth: '1995-02-28',
    primaryEmail: 'noah.rodriguez@example.com',
    primaryMobile: '+52 55 1234 5678',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP011'
  },
  {
    id: 12,
    fullName: 'Isabella Lee',
    vesselName: 'Stellar Traveler',
    nationality: 'South Korea',
    dateOfBirth: '1991-11-10',
    primaryEmail: 'isabella.lee@example.com',
    primaryMobile: '+82 2 9876 5432',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'External',
    employeeID: 'EMP012'
  },
  {
    id: 13,
    fullName: 'Oliver Martinez',
    vesselName: 'Cosmic Explorer',
    nationality: 'Spain',
    dateOfBirth: '1984-04-03',
    primaryEmail: 'oliver.martinez@example.com',
    primaryMobile: '+34 91 876 5432',
    primaryStatus: 'Inactive',
    statusDescription: 'Resigned',
    source: 'Internal',
    employeeID: 'EMP013'
  },
  {
    id: 14,
    fullName: 'Emma White',
    vesselName: 'Oceanic Voyager',
    nationality: 'Australia',
    dateOfBirth: '1996-08-17',
    primaryEmail: 'emma.white@example.com',
    primaryMobile: '+61 4321-9876',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'External',
    employeeID: 'EMP014'
  },
  {
    id: 15,
    fullName: 'Alexander Kim',
    vesselName: 'Deep Space Explorer',
    nationality: 'Russia',
    dateOfBirth: '1986-12-04',
    primaryEmail: 'alexander.kim@example.com',
    primaryMobile: '+7 495 123 4567',
    primaryStatus: 'Inactive',
    statusDescription: 'Retired',
    source: 'Internal',
    employeeID: 'EMP015'
  },
  {
    id: 16,
    fullName: 'Ella Wong',
    vesselName: 'Starlight Navigator',
    nationality: 'Singapore',
    dateOfBirth: '1990-03-28',
    primaryEmail: 'ella.wong@example.com',
    primaryMobile: '+65 9123 4567',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP016'
  },
  {
    id: 17,
    fullName: 'William Garcia',
    vesselName: 'Galactic Traveller',
    nationality: 'Brazil',
    dateOfBirth: '1989-05-15',
    primaryEmail: 'william.garcia@example.com',
    primaryMobile: '+55 21 98765 4321',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'External',
    employeeID: 'EMP017'
  },
  {
    id: 18,
    fullName: 'Grace Park',
    vesselName: 'Interstellar Explorer',
    nationality: 'South Korea',
    dateOfBirth: '1993-10-08',
    primaryEmail: 'grace.park@example.com',
    primaryMobile: '+82 10 8765 4321',
    primaryStatus: 'Inactive',
    statusDescription: 'Resigned',
    source: 'External',
    employeeID: 'EMP018'
  },
  {
    id: 19,
    fullName: 'Benjamin Taylor',
    vesselName: 'Deep Blue Explorer',
    nationality: 'USA',
    dateOfBirth: '1987-06-22',
    primaryEmail: 'benjamin.taylor@example.com',
    primaryMobile: '+1 555-9876',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP019'
  },
  {
    id: 20,
    fullName: 'Sophie Hernandez',
    vesselName: 'Solar Voyager',
    nationality: 'Spain',
    dateOfBirth: '1994-03-11',
    primaryEmail: 'sophie.hernandez@example.com',
    primaryMobile: '+34 91 432 5678',
    primaryStatus: 'Inactive',
    statusDescription: 'Resigned',
    source: 'External',
    employeeID: 'EMP020'
  },
  {
    id: 21,
    fullName: 'Jackson Chen',
    vesselName: 'Celestial Explorer',
    nationality: 'China',
    dateOfBirth: '1985-09-28',
    primaryEmail: 'jackson.chen@example.com',
    primaryMobile: '+86 21 9876 5432',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'Internal',
    employeeID: 'EMP021'
  },
  {
    id: 22,
    fullName: 'Eva Miller',
    vesselName: 'Stellar Voyager',
    nationality: 'Germany',
    dateOfBirth: '1990-12-15',
    primaryEmail: 'eva.miller@example.com',
    primaryMobile: '+49 123 456 7890',
    primaryStatus: 'Active',
    statusDescription: 'Regular',
    source: 'External',
    employeeID: 'EMP022'
  },
  {
    id: 23,
    fullName: 'Daniel Kim',
    vesselName: 'Skyward Navigator',
    nationality: 'South Korea',
    dateOfBirth: '1988-05-03',
    primaryEmail: 'daniel.kim@example.com',
    primaryMobile: '+82 2 8765 4321',
    primaryStatus: 'Inactive',
    statusDescription: 'Retired',
    source: 'Internal',
    employeeID: 'EMP023'
  }
]